In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('Bengaluru_House_Data.csv')
data.drop(columns=['area_type','availability','availability'],inplace=True)

In [3]:
data

,location,size,society,total_sqft,bath,balcony,price
0,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...
13315,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [12]:
data.dropna(inplace=True)
data.location.value_counts()
data['location'] = data['location'].apply(lambda x:x.strip())

In [13]:
location_new=data.groupby('location')['location'].agg('count').sort_values(ascending=False)

In [14]:
location_new

location
Whitefield                        398
Sarjapur  Road                    310
Electronic City                   238
Kanakpura Road                    216
Thanisandra                       215
                                 ...
Kattigenahalli                      1
Kashi Nagar                         1
Kamakshipalya                       1
Kalhalli                            1
Yeshwanthpur Industrial Suburb      1
Name: location, Length: 626, dtype: int64

In [15]:
location_less_than_10 =location_new[location_new <=10]

In [17]:
location_less_than_10

location
 Banaswadi                        1
 Bhoganhalli                      1
 Devarabeesana Halli              4
 Devarachikkanahalli              8
 Electronic City                  2
                                 ..
Wilson Garden                     3
Yelachenahalli                    8
Yelenahalli                       3
Yemlur                            3
Yeshwanthpur Industrial Suburb    1
Name: location, Length: 491, dtype: int64

In [18]:
data['location'] = data['location'].apply(lambda x:'other' if x in location_less_than_10 else x)

In [19]:
data['location'].value_counts()

location
other                 1443
Whitefield             398
Sarjapur  Road         310
Electronic City        238
Kanakpura Road         216
                      ...
Neeladri Nagar          11
Billekahalli            11
Bharathi Nagar          11
Pattandur Agrahara      11
AECS Layout             11
Name: count, Length: 144, dtype: int64

In [20]:
data

,location,size,society,total_sqft,bath,balcony,price
0,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
3,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
5,Whitefield,2 BHK,DuenaTa,1170,2.0,1.0,38.00
11,Whitefield,4 Bedroom,Prrry M,2785,5.0,3.0,295.00
...,...,...,...,...,...,...,...
13313,Uttarahalli,3 BHK,Aklia R,1345,2.0,1.0,57.00
13314,Green Glen Layout,3 BHK,SoosePr,1715,3.0,3.0,112.00
13315,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13317,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00

In [21]:
data['size'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '3 Bedroom', '1 RK', '4 BHK',
       '1 BHK', '5 BHK', '11 BHK', '5 Bedroom', '9 BHK', '2 Bedroom',
       '6 BHK', '7 BHK', '6 Bedroom'], dtype=object)

In [22]:
data['bedrooms']=data['size'].apply(lambda x:x.split(' ')[0])

In [23]:
data

,location,size,society,total_sqft,bath,balcony,price,bedrooms
0,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2
1,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,4
3,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3
5,Whitefield,2 BHK,DuenaTa,1170,2.0,1.0,38.00,2
11,Whitefield,4 Bedroom,Prrry M,2785,5.0,3.0,295.00,4
...,...,...,...,...,...,...,...,...
13313,Uttarahalli,3 BHK,Aklia R,1345,2.0,1.0,57.00,3
13314,Green Glen Layout,3 BHK,SoosePr,1715,3.0,3.0,112.00,3
13315,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00,5
13317,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00,2
13318,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00,4

In [24]:
data.total_sqft.unique()

array(['1056', '2600', '1521', ..., '1919', '2111', '4689'],
      shape=(1682,), dtype=object)

In [37]:
def clean(sqft):
    if isinstance(sqft, (int, float)):
        return float(sqft)

    tokens = str(sqft).split('-')

    if len(tokens) == 2:
        return (float(tokens[0]) + float(tokens[1])) / 2

    try:
        return float(sqft)
    except:
        return None

In [38]:
clean('200')

200.0

In [39]:
data['total_sqft']=data['total_sqft'].apply(clean)
data.total_sqft.unique()

array([1056., 2600., 1521., ..., 1919., 2111., 4689.], shape=(1623,))

In [40]:
data.dropna(inplace=True)
data.describe()

         total_sqft         bath      balcony        price
count   7481.000000  7481.000000  7481.000000  7481.000000
mean    1507.516043     2.457693     1.630531    96.767141
std      935.083274     0.881241     0.780510   105.396046
min       11.000000     1.000000     0.000000     8.000000
25%     1115.000000     2.000000     1.000000    49.490000
50%     1310.000000     2.000000     2.000000    69.610000
75%     1656.000000     3.000000     2.000000   105.000000
max    36000.000000     9.000000     3.000000  2700.000000

In [41]:
data['bedrooms'] = data['bedrooms'].astype(int)

In [42]:
data['sqft_per_bed'] = data['total_sqft'] / data['bedrooms']

In [43]:
data.sqft_per_bed.describe()

count     7481.000000
mean       588.424430
std        224.966082
min          3.666667
25%        500.000000
50%        567.333333
75%        632.500000
max      11666.666667
Name: sqft_per_bed, dtype: float64

In [44]:
data1=data[data['sqft_per_bed'] >=300]

In [45]:
data1

,location,size,society,total_sqft,bath,balcony,price,bedrooms,sqft_per_bed
0,Electronic City Phase II,2 BHK,Coomee,1056.0,2.0,1.0,39.07,2,528.000000
1,Chikka Tirupathi,4 Bedroom,Theanmp,2600.0,5.0,3.0,120.00,4,650.000000
3,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00,3,507.000000
5,Whitefield,2 BHK,DuenaTa,1170.0,2.0,1.0,38.00,2,585.000000
11,Whitefield,4 Bedroom,Prrry M,2785.0,5.0,3.0,295.00,4,696.250000
...,...,...,...,...,...,...,...,...,...
13313,Uttarahalli,3 BHK,Aklia R,1345.0,2.0,1.0,57.00,3,448.333333
13314,Green Glen Layout,3 BHK,SoosePr,1715.0,3.0,3.0,112.00,3,571.666667
13315,Whitefield,5 Bedroom,ArsiaEx,3453.0,4.0,0.0,231.00,5,690.600000
13317,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141.0,2.0,1.0,60.00,2,570.500000
13318,Padmanabhanagar,4 BHK,SollyCl,4689.0,4.0,1.0,488.00,4,1172.250000

In [46]:
data1['price_per_sqft'] = data1['price']*100000/data1['total_sqft']

C:\Users\avtaa\AppData\Local\Temp\ipykernel_4932\99980699.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1['price_per_sqft'] = data1['price']*100000/data1['total_sqft']

In [47]:
data1

,location,size,society,total_sqft,bath,balcony,price,bedrooms,sqft_per_bed,price_per_sqft
0,Electronic City Phase II,2 BHK,Coomee,1056.0,2.0,1.0,39.07,2,528.000000,3699.810606
1,Chikka Tirupathi,4 Bedroom,Theanmp,2600.0,5.0,3.0,120.00,4,650.000000,4615.384615
3,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00,3,507.000000,6245.890861
5,Whitefield,2 BHK,DuenaTa,1170.0,2.0,1.0,38.00,2,585.000000,3247.863248
11,Whitefield,4 Bedroom,Prrry M,2785.0,5.0,3.0,295.00,4,696.250000,10592.459605
...,...,...,...,...,...,...,...,...,...,...
13313,Uttarahalli,3 BHK,Aklia R,1345.0,2.0,1.0,57.00,3,448.333333,4237.918216
13314,Green Glen Layout,3 BHK,SoosePr,1715.0,3.0,3.0,112.00,3,571.666667,6530.612245
13315,Whitefield,5 Bedroom,ArsiaEx,3453.0,4.0,0.0,231.00,5,690.600000,6689.834926
13317,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141.0,2.0,1.0,60.00,2,570.500000,5258.545136
13318,Padmanabhanagar,4 BHK,SollyCl,4689.0,4.0,1.0,488.00,4,1172.250000,10407.336319

In [50]:
data2 = data1[data1['price_per_sqft'] > 2000]

In [53]:
data2.drop(columns = ['size','price_per_sqft','sqft_per_bed'],axis =1,inplace=True)

C:\Users\avtaa\AppData\Local\Temp\ipykernel_4932\744557028.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2.drop(columns = ['size','price_per_sqft','sqft_per_bed'],axis =1,inplace=True)

In [76]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_transformer

col_trans = make_column_transformer(
    (OneHotEncoder(sparse_output=False), ['location']),
    remainder='passthrough'
)

In [77]:
lr = LinearRegression()
scaler = StandardScaler()
model = make_pipeline(col_trans,scaler,lr)

In [78]:
X = data2.drop(columns=['price'])
y = data2['price']

In [79]:
X.select_dtypes(include='object').columns

Index(['location'], dtype='object')

In [80]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0
)

model.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [81]:
from sklearn.metrics import r2_score

y_pred = model.predict(X_test)

score = r2_score(y_test, y_pred)
print(score)

0.732954654713815

In [83]:
model.score(X_test,y_test)

0.732954654713815

In [84]:
import pickle as pk
pk.dump(model,open('House_prediction.pkl','wb'))

In [85]:
data2.to_csv('Cleaned_data.csv')

In [86]:
import sys
print(sys.executable)

D:\anaconda\python.exe

In [87]:
import sys
!{sys.executable} -m pip install streamlit

Requirement already satisfied: streamlit in d:\anaconda\lib\site-packages (1.51.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in d:\anaconda\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in d:\anaconda\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in d:\anaconda\lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in d:\anaconda\lib\site-packages (from streamlit) (8.2.1)
Requirement already satisfied: numpy<3,>=1.23 in d:\anaconda\lib\site-packages (from streamlit) (2.3.5)
Requirement already satisfied: packaging<26,>=20 in d:\anaconda\lib\site-packages (from streamlit) (25.0)
Requirement already satisfied: pandas<3,>=1.4.0 in d:\anaconda\lib\site-packages (from streamlit) (2.3.3)
Requirement already satisfied: pillow<13,>=7.1.0 in d:\anaconda\lib\site-packages (from streamlit) (12.0.0)
Requirement already satisfied: protobuf<7,>=3.20 in d:\anaconda\lib\site-packages (from streamlit) (5.29.3)
Requirement already satisfied: pyarrow<22,>=7.0 in d:\anaconda\lib\site-packages (from streamlit) (21.0.0)
Requirement already satisfied: requests<3,>=2.27 in d:\anaconda\lib\site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in d:\anaconda\lib\site-packages (from streamlit) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in d:\anaconda\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in d:\anaconda\lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in d:\anaconda\lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in d:\anaconda\lib\site-packages (from streamlit) (3.1.45)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in d:\anaconda\lib\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: jinja2 in d:\anaconda\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in d:\anaconda\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.0)
Requirement already satisfied: narwhals>=1.14.2 in d:\anaconda\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.7.0)
Requirement already satisfied: colorama in d:\anaconda\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in d:\anaconda\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in d:\anaconda\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\anaconda\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\anaconda\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\anaconda\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda\lib\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda\lib\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.11.12)
Requirement already satisfied: attrs>=22.2.0 in d:\anaconda\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in d:\anaconda\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in d:\anaconda\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in d:\anaconda\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.28.0)
Requirement already satisfied: six>=1.5 in d:\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\anaconda\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.2)

In [ ]:
import sys
!{sys.executable} -m streamlit run app.py